jenkins:
  systemMessage: "Welcom to LV CI Jenkins"

unclassified:
  location:
    url: http://localhost:8080/

jobs:
  - script: >
      job('Job_DSL_Seed') {
        scm {
          git {
            remote {
              url 'http://gerrit:8080/pipelines'
            }
          }
        }
        steps {
          jobDsl {
            targets '*.groovy'
          }
        }
      }
